replicaCount: 2

image:
  repository: varshithkumar8/employee-management
  tag: v10
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

configMap:
  name: employee-config
  dbHost: postgres-service
  dbPort: "5432"

secret:
  name: postgres-secret
  database: employee_db
  username: postgres
  password: admin123

postgres:
  replicaCount: 1

  image:
    repository: postgres
    tag: "17"
    pullPolicy: IfNotPresent

  service:
    name: postgres-service
    port: 5432

  pvc:
    claimName: postgres-pvc

  container:
    name: postgres

  storage:
    mountPath: /var/lib/postgresql/data

  storageSize: 2Gi

  pgdata: /var/lib/postgresql/data/pgdata
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  path: /
  port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /
  port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5