apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-management

spec:
  replicas: 2

  selector:
    matchLabels:
      app: employee-management

  template:
    metadata:
      labels:
        app: employee-management

    spec:
      containers:
      - name: employee-app
        image: varshithkumar8/employee-management:v10

        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: employee-config

        - secretRef:
            name: postgres-secret

        volumeMounts:
        - name: employee-storage
          mountPath: /app/database

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

      volumes:
      - name: employee-storage
        persistentVolumeClaim:
          claimName: employee-pvc