apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: {{ .Values.postgres.replicaCount }}

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: {{ .Values.postgres.container.name }}

        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.postgres.service.port }}

        envFrom:
        - secretRef:
            name: {{ .Values.secret.name }}

        env:
        - name: PGDATA
          value: {{ .Values.postgres.pgdata | quote }}

        volumeMounts:
        - name: postgres-storage
          mountPath: {{ .Values.postgres.storage.mountPath }}

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.pvc.claimName }}