name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Employee Management CI/CD"]
    types:
      - completed

jobs:
  update-manifest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm image tag
        run: |
          sed -i "s/tag:.*/tag: latest/" employee-chart/values-prod.yaml

      - name: Commit updated Helm values
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add employee-chart/values-prod.yaml

          git diff --cached --quiet || \
          git commit -m "Update production image"

          git push